project:
  type: book

book:
  title: "Cancionero de la Alicantina"
  author: "Tuna de Medicina de Alicante"
  date: "10/27/2025"
  chapters:
    - index.qmd
    - a_la_luz_de_la_luna.qmd
    - alicantina.qmd
    - maria_va.qmd
    - perdoname.qmd

bibliography: references.bib

format:
  html:
    theme:
      - lux
      - brand
  pdf:
    documentclass: scrreprt



